# Site settings
title: Jeremy Parmenter
email: jeremyrparmenter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Jeremy Parmenter. Place to leave my writings of
  things I love like coding, books, movies, or other thoughs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jparmenter.github.com" # the base hostname & protocol for your site
twitter_username: jparmesan
github_username:  jparmenter

# Build settings
markdown: kramdown
